spring:
#  config:
#    activate:
#      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/alcohol-world
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-expired-time-ms: ${JWT_EXPIRED_DATE}

image:
  upload-dir: "C:/Users/TONYWOO/OneDrive/바탕 화면/Coding/항해프로젝트/alcohol_world/alchohol/src/main/resources/static"

